{% set name = "pyseobnr" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyseobnr-{{ version }}.tar.gz
  sha256: 4cc1a89b88ef5fd4cc88c09c6bddfc1b3cc521e1877bc2dc06ea7694724d8347
  patches:
    - nolalsuite-in-pyproject.patch
    - pandas-item-access-in-test.patch

build:
  skip: true  # [win]
  script: |
    find . -name "*.cpp" -delete
    {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy <1.13.0                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - cython
    - numpy
    - pip
    - python
    - scipy <1.13.0
    - setuptools
    - setuptools-scm >=3.4.3
    - wheel

  run:
    - h5py
    - matplotlib-base
    - numba
    - numexpr
    - {{ pin_compatible('numpy') }}
    - numpy >=1.23.0
    - pygsl_lite
    - python
    - python-lal
    - python-lalsimulation
    - qnm
    - rich
    - {{ pin_compatible('scipy') }}
    - scipy >=1.8.0
    - scri
    - setuptools

test:
  requires:
    - pip
    - pytest
    - pandas
    - pycbc
  source_files:
    - test/
  commands:
    # This is disabled because scri and sxs have issues on pypi
    #- python -m pip check
    - python -m pip show pyseobnr
    - python -m pytest test/ -ra

about:
  summary: Gravitational wave modelling within the effective-one-body framework
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://git.ligo.org/waveforms/software/pyseobnr
  dev_url: https://git.ligo.org/waveforms/software/pyseobnr
  doc_url: https://waveforms.docs.ligo.org/software/pyseobnr/

extra:
  recipe-maintainers:
    - raffienficiaud
    - duncanmmacleod
    - lorenzopompili00
